[bastion]
bastion-01 ansible_host=13.206.109.28

[control_plane]
master-01 ansible_host=10.0.11.38

[workers]
worker-01 ansible_host=10.0.12.70
worker-02 ansible_host=10.0.12.183

[kube_nodes:children]
control_plane
workers

[kube_nodes:vars]
ansible_ssh_common_args='-o ProxyJump=ubuntu@13.206.109.28'