[bastion]
bastion-01 ansible_host=13.206.194.232

[control_plane]
master-01 ansible_host=10.0.11.252

[workers]
worker-01 ansible_host=10.0.12.4
worker-02 ansible_host=10.0.12.213

[kube_nodes:children]
control_plane
workers

[kube_nodes:vars]
ansible_ssh_common_args='-o ProxyJump=ubuntu@13.206.194.232'