[control_plane]
master-01 ansible_host=10.0.11.90

[workers]
worker-01 ansible_host=10.0.12.178
worker-02 ansible_host=10.0.12.114

[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-o ProxyJump=ubuntu@43.205.254.25'